language: node_js
node_js:
  - 8

after_success:
  - npm install
  - npm run lint
  - npm run test

notifications:
  email:
    recipients:
    - saurabhnemade@yandex.com
    on_success: always
    on_failure: always
